AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-patientcheckoutbucket
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-patientcheckouttopic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.denisarruda.patientcheckout.boundary.PatientCheckoutLambda::handler
      Runtime: java25
      Architectures:
      - x86_64
      MemorySize: 512
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutDLQ
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-patientcheckoutbucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3 # More info about S3 Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  BillManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: com.denisarruda.patientcheckout.boundary.BillManagementLambda::handler
      Runtime: java25
      Architectures:
      - x86_64
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SNSEvent:
          Type: SNS # More info about SNS Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sns
          Properties:
            Topic: !Ref PatientCheckoutTopic
  ErrorHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patientcheckout
      Handler: com.denisarruda.patientcheckout.boundary.ErrorHandler::handleError
      Runtime: java25
      Architectures:
      - x86_64
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutDLQ
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
